<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Logger\Handler;

use Magento\Framework\Logger\Handler\System;

class Critical extends System
{
    /**
     * @var string
     */
    const DEFAULT_DEBUG_FILE_NAME = '/var/log/pay2.log';

    /**
     * @var string
     */
    protected $fileName = self::DEFAULT_DEBUG_FILE_NAME;
}
