<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Gateway\Request\Builder;

use Magento\Payment\Gateway\Data\PaymentDataObjectInterface;
use Magento\Payment\Gateway\Request\BuilderInterface;
use Magento\Sales\Model\Order\Payment;

class Shipping implements BuilderInterface
{

    /**
     * @inheritDoc
     */
    public function build(array $buildSubject)
    {
        /** @var PaymentDataObjectInterface $paymentDataObject */
        $paymentDataObject = $buildSubject['payment'];

        /** @var Payment */
        $payment = $paymentDataObject->getPayment();
        $order = $payment->getOrder();

        if ($order->getIsVirtual()) {
            return [];
        }

        $address = $order->getShippingAddress() ? $order->getShippingAddress() : $order->getBillingAddress();
        $street = $address->getStreet();
        $postCode = str_replace('-', '', $address->getPostcode());

        $data = [
            'shipping' => [
                'name' => $order->getShippingDescription(),
                'amount' => $order->getShippingAmount(),
                'address' => [
                    'street' => $street[0],
                    'number' => $street[1],
                    'complement' => isset($street[3]) ? $street[3] : '',
                    'neighborhood' => isset($street[2]) ? $street[2] : '',
                    'city' => $address->getCity(),
                    'state' => $address->getRegionCode(),
                    'postal_code' => $postCode
                ]
            ]
        ];

        return $data;
    }
}
