<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Block;

use Magento\Framework\View\Element\Template\Context;
use Pay2\Pix\Gateway\Config\Config;

class Form extends \Magento\Payment\Block\Form
{

    /**
     * @var Config
     */
    protected $config;

    /**
     * @param \Magento\Framework\View\Element\Template\Context $context
     * @param \Pay2\Pix\Gateway\Config\Config $config
     * @param array $data
     */
    public function __construct(
        Context $context,
        Config $config,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->config = $config;
    }

    /**
     * Retrieve payment config
     * @return Config
     */
    public function getConfig(): Config
    {
        return $this->config;
    }
}
