<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Block;

use Magento\Framework\Phrase;
use Magento\Payment\Block\ConfigurableInfo;

class Info extends ConfigurableInfo
{
    /**
     * @inheritDoc
     * @var string
     */
    protected $_template = 'Pay2_Pix::sales/order/payment/info.phtml';

    /**
     * Returns label
     * @param string $field
     * @return Phrase
     */
    protected function getLabel($field): Phrase
    {
        return __($field);
    }

    /**
     * Check if payment is paid
     * @return boolean
     */
    public function isPaymentPaid()
    {
        $status = $this->getInfo()->getAdditionalInformation('status');
        return $status === 'APPROVED';
    }

    /**
     * Check if payment is refunded
     * @return boolean
     */
    public function isPaymentRefunded()
    {
        $status = $this->getInfo()->getAdditionalInformation('status');
        return $status === 'REFUNDED';
    }

    /**
     * Check if payment was expired
     * @return boolean
     */
    public function isPaymentExpired()
    {
        $status = $this->getInfo()->getAdditionalInformation('status');
        return $status === 'EXPIRED';
    }

    /**
     * Check if payment was voided
     * @return boolean
     */
    public function isPaymentVoided()
    {
        $status = $this->getInfo()->getAdditionalInformation('status');
        return $status === 'VOIDED';
    }

    /**
     * Check if payment is pending
     * @return boolean
     */
    public function isPaymentPending()
    {
        $status = $this->getInfo()->getAdditionalInformation('status');
        return !$status || $status === 'CREATED';
    }
}
