<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Model\Checkout;

use Magento\Checkout\Model\ConfigProviderInterface;
use Pay2\Pix\Gateway\Config\Config;

class ConfigProvider implements ConfigProviderInterface
{

    /**
     * Payment code
     */
    const CODE = 'pay2_pix';

    /**
     * @var Config
     */
    protected $config;

    /**
     * @param \Pay2\Pix\Gateway\Config\Config $config
     */
    public function __construct(Config $config)
    {
        $this->config = $config;
    }

    /**
     * @inheritDoc
     */
    public function getConfig()
    {

        $configData = [
            'active' => $this->config->getActive(),
            'expire_time' => $this->config->getExpireTime(),
            'instructions' => $this->config->getInstructions(),
            'error_message' => $this->config->getErrorMessage(),
        ];

        $config = [
            'payment' => [
                self::CODE => $configData
            ]
        ];

        return $config;
    }
}
