<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Gateway\Validator;

use Magento\Payment\Gateway\Validator\AbstractValidator;
use Magento\Payment\Gateway\Validator\ResultInterfaceFactory;
use Pay2\Pix\Gateway\Config\Config;

class AuthorizeResponse extends AbstractValidator
{

    /**
     * @var Config
     */
    protected $config;

    /**
     * @param \Magento\Payment\Gateway\Validator\ResultInterfaceFactory $resultFactory
     * @param \Pay2\Pix\Gateway\Config\Config $config
     */
    public function __construct(
        ResultInterfaceFactory $resultFactory,
        Config $config
    ) {
        parent::__construct($resultFactory);
        $this->config = $config;
    }

    /**
     * @inheritdoc
     */
    public function validate(array $validationSubject)
    {
        $response = $validationSubject['response'];

        $isValid = true;
        $errorMessages = [];

        if (
            !$response
            || !isset($response['data']['raw_data'])
            || !isset($response['data']['raw_data']['data']['instantPayment'])
        ) {
            $isValid = false;
            $errorMessages[] = $this->config->getErrorMessage();
        }

        return $this->createResult($isValid, $errorMessages);
    }
}
