<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Gateway\Validator;

use Magento\Payment\Gateway\Validator\AbstractValidator;

class RefundResponse extends AbstractValidator
{

    /**
     * @inheritdoc
     */
    public function validate(array $validationSubject)
    {
        $response = $validationSubject['response'];

        $isValid = true;
        $errorMessages = [];

        if (
            !$response
            || !isset($response['data']['status'])
        ) {
            $isValid = false;
        }

        if (!$isValid && isset($response['message'])) {
            $errorMessages[] = $response['message'];
        }

        return $this->createResult($isValid, $errorMessages);
    }
}
