/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

define([
    'Magento_Checkout/js/view/payment/default'
], function (Component) {
    'use strict';

    return Component.extend({
        defaults: {
            template: 'Pay2_Pix/payment/method-renderer/payment-form'
        },
        getInstructions: function () {
            return window.checkoutConfig.payment.pay2_pix.instructions.split("\n").join('<br/>');
        }
    });
});
