<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Gateway\Http\TransferFactory;

use Magento\Payment\Gateway\Http\TransferBuilder;
use Magento\Payment\Gateway\Http\TransferFactoryInterface;
use Magento\Payment\Gateway\Http\TransferInterface;
use Pay2\Pix\Gateway\Config\Config;

class Authorize implements TransferFactoryInterface
{
    /**
     * @var TransferBuilder
     */
    protected $transferBuilder;

    /**
     * @var Config
     */
    protected $config;

    /**
     * @param TransferBuilder $transferBuilder
     * @param Config $config
     */
    public function __construct(
        TransferBuilder $transferBuilder,
        Config $config
    ) {
        $this->transferBuilder = $transferBuilder;
        $this->config = $config;
    }

    /**
     * Builds gateway transfer object
     * @param array $request
     * @return TransferInterface
     */
    public function create(array $request)
    {
        $url = $this->config->getGatewayUrl();
        return $this->transferBuilder
            ->setMethod('POST')
            ->setUri($url . '/transactions')
            ->setHeaders([
                'Content-Type: application/json',
                'Accept: application/json',
                'Authorization: Bearer ' . $this->config->getAccessToken(),
            ])
            ->setBody($request)
            ->build();
    }
}
