<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Gateway\Config;

use Pay2\Pix\Model\Config\Source\Environment;
use Magento\Payment\Gateway\Config\Config as PaymentConfig;

class Config extends PaymentConfig
{

    const ACTIVE = 'active';
    const TITLE = 'title';
    const ENVIRONMENT = 'environment';
    const ACCOUNT_ID = 'account_id';
    const PIX_KEY = 'pix_key';
    const ACCESS_TOKEN = 'access_token';
    const EXPIRE_TIME = 'expire_time';
    const INSTRUCTIONS = 'instructions';
    const ERROR_MESSAGE = 'error_message';
    const DEBUG = 'debug';

    const PRODUCTION_URL = 'https://api.pay2.com.br/api';
    const SANDBOX_URL = 'https://sandbox.pay2.com.br/api';

    /**
     * @return bool
     */
    public function getActive()
    {
        return (bool)$this->getValue(self::ACTIVE);
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return (string)$this->getValue(self::TITLE);
    }

    /**
     * @return string
     */
    public function getEnvironment()
    {
        return (string)$this->getValue(self::ENVIRONMENT);
    }

    /**
     * @return string
     */
    public function getAccountId()
    {
        return (string)$this->getValue(self::ACCOUNT_ID);
    }

    /**
     * @return string
     */
    public function getPixKey()
    {
        return (string)$this->getValue(self::PIX_KEY);
    }

    /**
     * @return string
     */
    public function getAccessToken()
    {
        return (string)$this->getValue(self::ACCESS_TOKEN);
    }

    /**
     * @return int
     */
    public function getExpireTime()
    {
        return (int)$this->getValue(self::EXPIRE_TIME);
    }

    /**
     * @return string
     */
    public function getInstructions()
    {
        return (string)$this->getValue(self::INSTRUCTIONS);
    }

    /**
     * @return string
     */
    public function getErrorMessage()
    {
        return (string)$this->getValue(self::ERROR_MESSAGE);
    }

    /**
     * @return bool
     */
    public function getDebug()
    {
        return (bool)$this->getValue(self::DEBUG);
    }

    /**
     * @return bool
     */
    public function isDebugMode()
    {
        return $this->getDebug();
    }

    /**
     * @return bool
     */
    public function isProductionMode()
    {
        return $this->getEnvironment() === Environment::PRODUCTION;
    }

    /**
     * @return string
     */
    public function getGatewayUrl()
    {
        if ($this->isProductionMode()) {
            return self::PRODUCTION_URL;
        }

        return self::SANDBOX_URL;
    }
}
