<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Gateway\Converter;

use Magento\Payment\Gateway\Http\ConverterInterface;
use Magento\Framework\Serialize\Serializer\Json;

class ArrayToJson implements ConverterInterface
{
    /**
     * @var Json
     */
    protected $serializer;

    /**
     * @param \Magento\Framework\Serialize\Serializer\Json $serializer
     */
    public function __construct(Json $serializer)
    {
        $this->serializer = $serializer;
    }

    /**
     * @inheritdoc
     */
    public function convert($response)
    {
        return $this->serializer->serialize($response);
    }
}
