<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Gateway\Config\Handler;

use Magento\Payment\Gateway\Config\ValueHandlerInterface;
use Magento\Sales\Model\Order\Payment;

class CanVoid implements ValueHandlerInterface
{

    /**
     * Retrieve method configured value
     * @param array $subject
     * @param int|null $storeId
     * @return mixed
     */
    public function handle(array $subject, $storeId = null)
    {

        /** @var PaymentDataObjectInterface $paymentDataObject */
        $paymentDataObject = $subject['payment'];

        /** @var Payment $payment */
        $payment = $paymentDataObject->getPayment();

        return $payment instanceof Payment && !(bool)$payment->getAmountPaid();
    }
}
