<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Model\Config\Source;

use Magento\Framework\Data\OptionSourceInterface;
use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;

class Environment extends AbstractSource implements OptionSourceInterface
{

    const PRODUCTION = 'production';
    const SANDBOX = 'sandbox';

    /**
     * @inheritDoc
     * @return array
     */
    public function getAllOptions()
    {
        if ($this->_options === null) {
            $this->_options = [
                [
                    'label' => __('Production'),
                    'value' => self::PRODUCTION
                ],
                [
                    'label' => __('Sandbox'),
                    'value' => self::SANDBOX
                ]
            ];
        }
        return $this->_options;
    }

    /**
     * @inheritDoc
     * @return array
     */
    public function getOptionArray()
    {
        $_options = [];
        foreach ($this->getAllOptions() as $option) {
            $_options[$option['value']] = $option['label'];
        }
        return $_options;
    }
}
