<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Block\Checkout;

class Success extends \Magento\Checkout\Block\Onepage\Success
{

    /**
     * Retrieve payment object
     * @return \Magento\Sales\Api\Data\OrderPaymentInterface|null
     */
    public function getPayment()
    {

        $order = $this->_checkoutSession->getLastRealOrder();
        if (!$order) {
            return null;
        }

        $payment = $order->getPayment();
        if (!$payment) {
            return null;
        }

        return $payment;
    }

    /**
     * Retrieve payment additional information
     * @return array
     */
    public function getAdditionalInformation()
    {
        $payment = $this->getPayment();
        return ($payment) ? $payment->getAdditionalInformation() : [];
    }
}
