<?php

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Pay2
 * @package Pay2_Pix
 * @copyright Copyright (c) 2022 NobleCommerce
 * @author NobleCommerce <hello@noblecommerce.io>
 *
 * See LICENSE.md for license details.
 */

declare(strict_types=1);

namespace Pay2\Pix\Gateway\Request;

use Magento\Payment\Gateway\Request\BuilderInterface;

class RequestBuilder implements BuilderInterface
{
    /**
     * @var BuilderInterface
     */
    protected $builderComposite;

    /**
     * @param \Magento\Payment\Gateway\Request\BuilderInterface $builder
     */
    public function __construct(BuilderInterface $builder)
    {
        $this->builderComposite = $builder;
    }

    /**
     * @inheritDoc
     */
    public function build(array $buildSubject)
    {
        return $this->builderComposite->build($buildSubject);
    }
}
